# -*- coding: utf-8 -*-
"""codsoft_task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgPfNZ04sG7TTrmAtr7pr_C6kmPJOo2Z
"""

import random
import string

def generate_password(length):
    # Define character sets
    upper = string.ascii_uppercase
    lower = string.ascii_lowercase
    digits = string.digits
    special = string.punctuation

    # Combine all character sets
    all_chars = upper + lower + digits + special

    # Generate a random password
    password = ''.join(random.choice(all_chars) for _ in range(length))

    return password

def main():
    # Prompt the user for the desired length of the password
    while True:
        try:
            length = int(input("Enter the desired length of the password: "))
            if length <= 0:
                print("Please enter a positive number.")
            else:
                break
        except ValueError:
            print("Invalid input. Please enter a numeric value.")

    # Generate the password
    password = generate_password(length)

    # Display the generated password
    print("Generated Password:", password)

if __name__ == "__main__":
    main()