# -*- coding: utf-8 -*-
"""codsoft_task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qlzOyoVH9GnOkt2tzWU4T99Wzg4ekaV7
"""

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y != 0:
        return x / y
    else:
        return "Error! Division by zero."

def calculator():
    print("Simple Calculator")
    print("Select operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")

    # Get operation choice from user
    choice = input("Enter choice (1/2/3/4): ")

    # Check if the choice is one of the valid options
    if choice in ['1', '2', '3', '4']:
        # Get numbers from user
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        # Perform the calculation based on the user's choice
        if choice == '1':
            print(f"The result of adding {num1} and {num2} is {add(num1, num2)}")
        elif choice == '2':
            print(f"The result of subtracting {num1} from {num2} is {subtract(num1, num2)}")
        elif choice == '3':
            print(f"The result of multiplying {num1} and {num2} is {multiply(num1, num2)}")
        elif choice == '4':
            result = divide(num1, num2)
            print(f"The result of dividing {num1} by {num2} is {result}")
    else:
        print("Invalid input")

# Run the calculator function
calculator()